name: wanderguard_companion_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.8
  dynamic_multi_step_form: ^1.1.5
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.2
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.2.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.7.0
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  zego_uikit: ^2.26.1
  zego_uikit_prebuilt_call: ^4.14.3
  zego_uikit_signaling_plugin: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    - lib/assets/
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/local_json/

    
