// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQWmEF_xjxCmi6KgMbjg2z66uLQNRtTQ',
    appId: '1:740065181238:web:a2e9744e0db39e0213e297',
    messagingSenderId: '740065181238',
    projectId: 'wanderguard-1e83a',
    authDomain: 'wanderguard-1e83a.firebaseapp.com',
    storageBucket: 'wanderguard-1e83a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejbQ4MsFeh6gu0MTLg6rXNxTzj3Cb5QY',
    appId: '1:740065181238:android:8d80f2c1fde86e6813e297',
    messagingSenderId: '740065181238',
    projectId: 'wanderguard-1e83a',
    storageBucket: 'wanderguard-1e83a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZQSmSmBsfH0kz0z698Z0hzgs_kQrh7Hk',
    appId: '1:740065181238:ios:170fa9424e0c797513e297',
    messagingSenderId: '740065181238',
    projectId: 'wanderguard-1e83a',
    storageBucket: 'wanderguard-1e83a.appspot.com',
    iosBundleId: 'com.example.wanderguardCompanionApp',
  );
}
